"""Vehicles added

Revision ID: aadb3f2f44e9
Revises: 4b8b6033d1e4
Create Date: 2024-01-26 18:46:15.899005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aadb3f2f44e9"
down_revision = "4b8b6033d1e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plate", sa.String(length=8), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plate"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicles")
    # ### end Alembic commands ###
